"""set ticket description to TEXT

Revision ID: 634bc2c34a64
Revises: b4de1bc229ab
Create Date: 2026-02-23 13:22:55.009095

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "634bc2c34a64"
down_revision: Union[str, Sequence[str], None] = "b4de1bc229ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tickets", sa.Column("title", sa.String(), nullable=False))
    op.add_column("tickets", sa.Column("description", sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tickets", "description")
    op.drop_column("tickets", "title")
    # ### end Alembic commands ###
