"""baseline

Revision ID: 8eac81735289
Revises: 
Create Date: 2026-02-21 15:45:27.432968

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eac81735289'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),

        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),

        sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),

        sa.Column('first_name', sa.String(), nullable=False),
        sa.Column('last_name', sa.String(), nullable=False),
        sa.Column('date_of_birth', sa.Date(), nullable=False),

        sa.Column('cpf', sa.String(), nullable=False),

        sa.Column('email', sa.String(length=140), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),

        sa.Column(
            'role',
            sa.Enum('ADMIN', 'TEAM_LEADER', 'AGENT', 'CUSTOMER', name='user_role'),
            server_default=sa.text("'CUSTOMER'"),
            nullable=False
        ),

        sa.Column('first_access', sa.Boolean(), server_default=sa.text('true'), nullable=False),
        sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),

        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email', name='uq_users_email'),
        sa.UniqueConstraint('cpf', name='uq_users_cpf'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.execute("DROP TYPE IF EXISTS user_role")
    # ### end Alembic commands ###
