"""update ticket

Revision ID: ab61b659289b
Revises: f3a7dbe7b4b9
Create Date: 2026-02-23 14:42:52.926346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab61b659289b'
down_revision: Union[str, Sequence[str], None] = 'f3a7dbe7b4b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('from_value', sa.Text(), nullable=True),
    sa.Column('to_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_audits_actor_user_id'), 'ticket_audits', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_ticket_audits_ticket_id'), 'ticket_audits', ['ticket_id'], unique=False)
    op.add_column('tickets', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'closed_at')
    op.drop_index(op.f('ix_ticket_audits_ticket_id'), table_name='ticket_audits')
    op.drop_index(op.f('ix_ticket_audits_actor_user_id'), table_name='ticket_audits')
    op.drop_table('ticket_audits')
    # ### end Alembic commands ###
