"""make team_leader_id nullable on tickets

Revision ID: f3a7dbe7b4b9
Revises: 634bc2c34a64
Create Date: 2026-02-23 14:18:42.327528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a7dbe7b4b9'
down_revision: Union[str, Sequence[str], None] = '634bc2c34a64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'team_leader_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'team_leader_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
